name: Get Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request Activation File (.alf)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v2
        id: get-alf
        with:
          unityVersion: 2022.3.56f1 # Matches your ci.yml version

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: UnityActivationFile
          path: ${{ steps.get-alf.outputs.filePath }}
